name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: Build
      run: yarn build

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: dist
        path: dist

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        access_token: ${{ secrets.github_pages_access_token }}
        folder: dist
        branch: gh-pages
